name: lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  # make workflow "callable" by others
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3'
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup Python v${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: pip install
      run: pip install -r requirements.txt -r requirements-dev.txt

    - name: lint using ruff
      # We could also use the official GitHub Actions integration.
      # https://beta.ruff.rs/docs/usage/#github-action
      # uses: chartboost/ruff-action@v1
      run: ruff --exclude webapp/converter --output-format github ./common ./v3 ./test-push-converter.py ./test-pull-converter.py

    - name: format using black
      # We could also use the official GitHub Actions integration.
      # https://black.readthedocs.io/en/stable/integrations/github_actions.html
      # uses: uses: psf/black@stable
      run: |
        black --exclude webapp/converter -S --check --diff ./common ./v3 ./test-push-converter.py ./test-pull-converter.py
